/*
 * blanco Framework
 * Copyright (C) 2004-2006 IGA Tosiki
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */
package blanco.cg;

import java.io.File;

import org.junit.jupiter.api.Test;

import blanco.cg.transformer.BlancoCgTransformerFactory;
import blanco.cg.valueobject.BlancoCgClass;
import blanco.cg.valueobject.BlancoCgField;
import blanco.cg.valueobject.BlancoCgMethod;
import blanco.cg.valueobject.BlancoCgSourceFile;

/**
 * Generation test for JavaScript.
 * 
 * @author IGA Tosiki
 */
public class BlancoCgTransformerJsTest {
    /**
     * The test for JavaScript.
     * 
     * @throws Exception
     */
    @Test
    public void testTransformerJs() throws Exception {
        final BlancoCgObjectFactory cgFactory = BlancoCgObjectFactory
                .getInstance();

        // Generates a source file.
        final BlancoCgSourceFile cgSourceFile = cgFactory.createSourceFile(
                "Myprog", "Class for testing");
        cgSourceFile.getLangDoc().getDescriptionList().add(
                "This class was auto-generated by blanco Framework.");

        // Generates the class.
        final BlancoCgClass cgClass = cgFactory.createClass("MyClass",
                "This class is for testing.");
        cgSourceFile.getClassList().add(cgClass);
        cgClass.getLangDoc().getTagList().add(
                cgFactory.createLangDocTag("author", null, "blanco Framework"));
        cgClass.getExtendClassList().add(
                cgFactory.createType("java.lang.Thread"));

        // Generates a field.
        final BlancoCgField cgField = cgFactory.createField("myField",
                "number", "Testing a numeric field.");
        cgClass.getFieldList().add(cgField);
        cgField.setDefault("Number(1)");

        // Generates a field.
        final BlancoCgField cgField2 = cgFactory.createField("myField2",
                "number", "Testing a numeric field.");
        cgClass.getFieldList().add(cgField2);
        cgField2.setAccess("public");
        cgField2.setDefault("Number(3)");

        // Generates a method.
        final BlancoCgMethod cgMethod = cgFactory.createMethod("myMethod",
                "Testing method.");
        cgClass.getMethodList().add(cgMethod);

        cgMethod.setAccess("private");

        // Adds parameters.
        cgMethod.getParameterList().add(
                cgFactory.createParameter("argString", "string", "String argument."));
        cgMethod.getParameterList().add(
                cgFactory.createParameter("argDate", "Date", "Date argument."));
        // Sets the return value.
        cgMethod.setReturn(cgFactory.createReturn("string", "Concatenated string."));

        cgMethod.getThrowList().add(
                cgFactory.createException("System.IO.IOException",
                        "If an I/O exception occurs."));

        // Adds the contents of the method.
        cgMethod.getLineList().add("// Testing concatenation.");
        cgMethod.getLineList().add("return argString + \", \" + argDate;");

        final BlancoCgTransformer cgTransformerJs = BlancoCgTransformerFactory
                .getJsSourceTransformer();
        cgTransformerJs.transform(cgSourceFile, new File("./tmp/blanco"));
    }
}
